spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/generic_ecommerce
spring.datasource.username=generic_ecommerce_user
spring.datasource.password=admin123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update